changed pre commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,61 +1,69 @@
 #!/bin/sh
-# axe-linter pre-commit
-# axe-linter-connector-win, -linux, -mac need to be installed and in path. Update line 32 with name of connector.
-# This script will setup the environment variables needed for the axe-linter-connector
-# and execute the axe-linter-connector. The output file will be reviewed and call back with exit codes:
-## 0 - No Accessibility Defects
-## 1 - Axe Linter Detected Accessibility Defects
-## 2 - Execution problem, or Axe-Linter Server unavailable.
-echo ""
+# exit 0
+# # axe-linter pre-commit
+# # axe-linter-connector-win, -linux, -mac need to be installed and in path. Update line 32 with name of connector.
+# # This script will setup the environment variables needed for the axe-linter-connector
+# # and execute the axe-linter-connector. The output file will be reviewed and call back with exit codes:
+# ## 0 - No Accessibility Defects
+# ## 1 - Axe Linter Detected Accessibility Defects
+# ## 2 - Execution problem, or Axe-Linter Server unavailable.
+# echo ""
 echo "Axe Linter Starting $(date)"
+# echo "in githooks directory"
+# node --version
+# jq --version
+# axe-linter-connector.exe --help
+# APIKey=d5e0df04-5cc6-4ab7-8cf7-987236ee0a14
+# # Setup variables for Axe Linter Server
+# export AXE_LINTER_SERVER_URL=https://axe-linter.deque.com
+# export AXE_LINTER_SERVER_PORT=3000
+# StatusCode=0
+# TempCode=0
+# # Configure verbose output.
+# VerboseOutput="true"
+# # Configure outfile: output in Generic Issue Import Format for in execution directory.
+# OutFile="axe-linter-report.json"
 
-# Setup variables for Axe Linter Server
-export AXE_LINTER_SERVER_URL=http://axelinterjensc.labdeque.com
-export AXE_LINTER_SERVER_PORT=3000
-StatusCode=0
-TempCode=0
-# Configure verbose output.
-VerboseOutput="true"
-# Configure outfile: output in Generic Issue Import Format for in execution directory.
-OutFile="axe-linter-report.json"
+# for i in $(git status --porcelain | sed s/^...//); do
+#    TempStatus=0
+# shopt -s nocasematch;
+#         if [[ $i == *.html ]] || [[ $i == *.js ]] || [[ $i == *.jsx ]]|| [[ $i == *.tsx ]]|| [[ $i == *.vue ]]|| [[ $i == *.htm ]]|| [[ $i == *.md ]]|| [[ $i == *.markdown ]];
+# #if [[ $i == *.html ]];
+#         then
+#            if $VerboseOutput; then
+#         echo "Accessibility check: file: $i"
+#             fi
+#         # execute axe-linter connector - Update with connector name
+#         # filePath=`find $i -type f -print`
+#         # axe-linter-connector.exe -s src\\Dashboard.js -d . --api-key d5e0df04-5cc6-4ab7-8cf7-987236ee0a14 -u https://axe-linter.deque.com
+#         axe-linter-connector.exe -s $i -d . --api-key $APIKey -u https://axe-linter.deque.com/
+#         # axe-linter-connector.exe -s $i -d . -u https://axe-linter.deque.com
 
-for i in $(git status --porcelain | sed s/^...//); do
-   TempStatus=0
-shopt -s nocasematch;
-        if [[ $i == *.html ]] || [[ $i == *.js ]] || [[ $i == *.jsx ]]|| [[ $i == *.tsx ]]|| [[ $i == *.vue ]]|| [[ $i == *.htm ]]|| [[ $i == *.md ]]|| [[ $i == *.markdown ]];
-#if [[ $i == *.html ]];
-        then
-           if $VerboseOutput; then
-        echo "Accessibility check: file: $i"
-            fi
-        # execute axe-linter connector - Update with connector name
-        axe-linter-connector-win.exe -s $i -d . -u $AXE_LINTER_SERVER_URL -p $AXE_LINTER_SERVER_PORT
+#         if [ ! -f "$OutFile" ];
+#            then
+#              echo "$OutFile Does Not Exit"
+#              exit 2
 
-        if [ ! -f "$OutFile" ];
-           then
-             echo "$OutFile Does Not Exit"
-             exit 2
+#            elif cat "$OutFile" | grep -q "BUG"; then
+#               if $VerboseOutput; then
+#               cat $OutFile
+#               fi
+# 	      echo ""
+#               echo "** Axe Linter Accessibility Issues Detected: $i"
+#               TempCode=1
+#            else
+#              echo "- No Axe Linter Connector Issues Detected in: $i"
+#         fi
+#            if (($TempCode !=0))
+#            then
+#             StatusCode=1
+#           fi
+#         # rm $OutFile
+#         fi
+# done
 
-           elif cat "$OutFile" | grep -q "BUG"; then
-              if $VerboseOutput; then
-              cat $OutFile
-              fi
-	      echo ""
-              echo "** Axe Linter Accessibility Issues Detected: $i"
-              TempCode=1
-           else
-             echo "- No Axe Linter Connector Issues Detected in: $i"
-        fi
-           if (($TempCode !=0))
-           then
-            StatusCode=1
-          fi
-        # rm $OutFile
-        fi
-done
-
-if (($StatusCode !=0))
-        then
-        echo "** Commit Failed due to Accessibility Issues **"
-        fi
-exit $StatusCode
+# if (($StatusCode !=0))
+#         then
+#         echo "** Commit Failed due to Accessibility Issues **"
+#         fi
+# exit $StatusCode
